import type { DiscoverItem, Wallpaper } from "./types";

export const WALLPAPERS: Wallpaper[] = [
  {
    id: "ridge",
    name: "Ridge Light",
    category: "Alpine",
    premium: false,
    purchased: true,
    src: "/env/ridge.jpg",
    motion: "drift",
    tracks: [
      { id: "r1", title: "High Meadow", artist: "Aether Room", seconds: 184 },
      { id: "r2", title: "Treeline", artist: "Aether Room", seconds: 212 },
      { id: "r3", title: "Cold Sun", artist: "North Glass", seconds: 196 },
      { id: "r4", title: "Switchback", artist: "North Glass", seconds: 168 },
      { id: "r5", title: "Last Light", artist: "Aether Room", seconds: 240 },
    ],
  },
  {
    id: "yosemite",
    name: "Valley Floor",
    category: "Alpine",
    premium: false,
    purchased: true,
    src: "/env/valley.jpg",
    motion: "still",
    tracks: [
      { id: "y1", title: "Granite", artist: "Aether Room", seconds: 200 },
      { id: "y2", title: "Mist Trail", artist: "North Glass", seconds: 188 },
      { id: "y3", title: "El Cap", artist: "Aether Room", seconds: 221 },
      { id: "y4", title: "Merced", artist: "Low Pressure", seconds: 174 },
      { id: "y5", title: "Half Dome", artist: "North Glass", seconds: 256 },
    ],
  },
  {
    id: "forest",
    name: "Canopy",
    category: "Forest",
    premium: false,
    purchased: true,
    src: "/env/forest.jpg",
    motion: "drift",
    tracks: [
      { id: "f1", title: "Needle Floor", artist: "Low Pressure", seconds: 190 },
      { id: "f2", title: "Green Dark", artist: "Aether Room", seconds: 210 },
      { id: "f3", title: "Sap", artist: "North Glass", seconds: 176 },
      { id: "f4", title: "After Rain", artist: "Low Pressure", seconds: 204 },
      { id: "f5", title: "Moss", artist: "Aether Room", seconds: 232 },
    ],
  },
  {
    id: "night",
    name: "Night Field",
    category: "Sky",
    premium: false,
    purchased: true,
    src: "/env/night.jpg",
    motion: "aurora",
    tracks: [
      { id: "n1", title: "Ion", artist: "North Glass", seconds: 248 },
      { id: "n2", title: "Quiet Band", artist: "Aether Room", seconds: 266 },
      { id: "n3", title: "Polar", artist: "Low Pressure", seconds: 198 },
      { id: "n4", title: "Drift Ice", artist: "North Glass", seconds: 214 },
      { id: "n5", title: "False Dawn", artist: "Aether Room", seconds: 280 },
    ],
  },
  {
    id: "tide",
    name: "Long Shore",
    category: "Ocean",
    premium: true,
    purchased: false,
    src: "/env/shore.jpg",
    motion: "tide",
    tracks: [
      { id: "t1", title: "Fetch", artist: "Low Pressure", seconds: 222 },
      { id: "t2", title: "Salt Room", artist: "Aether Room", seconds: 208 },
      { id: "t3", title: "Undertow", artist: "North Glass", seconds: 194 },
      { id: "t4", title: "Glass Water", artist: "Low Pressure", seconds: 236 },
      { id: "t5", title: "Harbour", artist: "Aether Room", seconds: 250 },
    ],
  },
  {
    id: "dune",
    name: "Warm Dune",
    category: "Desert",
    premium: true,
    purchased: false,
    src: "/env/dune.jpg",
    motion: "drift",
    tracks: [
      { id: "d1", title: "Sirocco", artist: "North Glass", seconds: 218 },
      { id: "d2", title: "Shadow Side", artist: "Aether Room", seconds: 202 },
      { id: "d3", title: "Quartz", artist: "Low Pressure", seconds: 186 },
      { id: "d4", title: "Noon", artist: "North Glass", seconds: 170 },
      { id: "d5", title: "Cooling", artist: "Aether Room", seconds: 244 },
    ],
  },
  {
    id: "aurora",
    name: "Thórsmörk",
    category: "Sky",
    premium: true,
    purchased: true,
    src: "/env/aurora.jpg",
    motion: "aurora",
    tracks: [
      { id: "a1", title: "Green Band", artist: "North Glass", seconds: 260 },
      { id: "a2", title: "Icefield", artist: "Aether Room", seconds: 274 },
      { id: "a3", title: "Fjall", artist: "Low Pressure", seconds: 228 },
      { id: "a4", title: "Ash", artist: "North Glass", seconds: 192 },
      { id: "a5", title: "Afterglow", artist: "Aether Room", seconds: 288 },
    ],
  },
  {
    id: "cloud",
    name: "Above Weather",
    category: "Sky",
    premium: true,
    purchased: false,
    src: "/env/cloud.jpg",
    motion: "drift",
    tracks: [
      { id: "c1", title: "Cirrus", artist: "Aether Room", seconds: 230 },
      { id: "c2", title: "Cabin", artist: "North Glass", seconds: 216 },
      { id: "c3", title: "Pressure", artist: "Low Pressure", seconds: 198 },
      { id: "c4", title: "Glide", artist: "Aether Room", seconds: 242 },
      { id: "c5", title: "Descent", artist: "North Glass", seconds: 205 },
    ],
  },
];

export const DISCOVER: DiscoverItem[] = [
  {
    id: "p1",
    title: "Editor's Desk",
    category: "prompts",
    author: "Studio North",
    blurb: "Tighten any draft without flattening the voice.",
    premium: false,
  },
  {
    id: "p2",
    title: "Socratic Loop",
    category: "prompts",
    author: "Lattice",
    blurb: "Ask until the real question appears.",
    premium: false,
  },
  {
    id: "p3",
    title: "Shot List",
    category: "prompts",
    author: "Frame",
    blurb: "Turn a scene into twelve stills.",
    premium: true,
  },
  {
    id: "v1",
    title: "Low Room",
    category: "voices",
    author: "Aether",
    blurb: "Quiet baritone, close mic.",
    premium: false,
  },
  {
    id: "v2",
    title: "Glass Alto",
    category: "voices",
    author: "Aether",
    blurb: "Cool, unhurried, indoor.",
    premium: true,
  },
  {
    id: "k1",
    title: "Field Notes",
    category: "packs",
    author: "Archive",
    blurb: "Paper textures, stamps, ruled night.",
    premium: false,
  },
  {
    id: "k2",
    title: "Night Lab",
    category: "packs",
    author: "Archive",
    blurb: "Oscilloscope chrome and dim type.",
    premium: true,
  },
  {
    id: "g1",
    title: "Librarian",
    category: "agents",
    author: "Aether",
    blurb: "Files, recall, and quiet filing.",
    premium: true,
  },
  {
    id: "g2",
    title: "Casting",
    category: "agents",
    author: "Frame",
    blurb: "Pairs image models to a brief.",
    premium: true,
  },
];
