import { chromium } from "playwright";
import { mkdir } from "node:fs/promises";
const OUT = "/workspace/screenshots/color-after";
await mkdir(OUT, { recursive: true });
const b = await chromium.launch({ headless: true });
const p = await b.newPage({ viewport: { width: 1280, height: 800 } });
await p.goto("http://127.0.0.1:8080/", { waitUntil: "networkidle" });
await p.waitForTimeout(700);
await p.screenshot({ path: `${OUT}/home.png`, animations: "disabled" });
const you = await p.evaluate(() => {
  const el = document.querySelector(".card-mini.you");
  if (!el) return null;
  const s = getComputedStyle(el);
  return { color: s.color, weight: s.fontWeight };
});
await p.locator(".card-name").first().click();
await p.waitForTimeout(400);
await p.screenshot({ path: `${OUT}/card.png`, animations: "disabled" });
await p.keyboard.press("Escape");
await p.waitForTimeout(200);
await p.getByRole("button", { name: "Settings" }).click();
await p.waitForTimeout(150);
await p.getByRole("button", { name: "Smart" }).click();
await p.waitForTimeout(250);
await p.getByRole("button", { name: "Smart Canvas" }).click();
await p.waitForTimeout(300);
await p.screenshot({ path: `${OUT}/canvas.png`, animations: "disabled" });
const stacked = await p.evaluate(() => Boolean(document.querySelector(".canvas-scene-bg")));
console.log({ you, stacked });
await b.close();
