import { chromium } from "playwright";
const browser = await chromium.launch({ args: ["--no-sandbox"] });
const page = await browser.newPage({ viewport: { width: 390, height: 844 } });
await page.goto("http://127.0.0.1:8080/", { waitUntil: "networkidle" });
await page.waitForTimeout(500);
await page.getByRole("button", { name: "Settings" }).click();
await page.waitForTimeout(250);
await page.getByText("Imagine", { exact: true }).click();
await page.waitForTimeout(800);
await page.locator(".imagine-tile").first().click();
await page.waitForTimeout(400);
await page.screenshot({ path: "/workspace/screenshots/t-imagine-open.png" });
const remix = await page.getByRole("button", { name: "Remix" }).count();
const videoBtn = await page.getByRole("button", { name: "Video" }).count();
const attach = await page.getByRole("button", { name: "Attach" }).count();
const x = await page.locator(".imagine-frame .win-x").count();
console.log({ remix, videoBtn, attach, x });
await page.locator(".imagine-frame .win-x").click();
await page.waitForTimeout(200);
await page.getByRole("button", { name: "Close" }).click().catch(async () => {
  await page.locator(".win-x").first().click();
});
await page.waitForTimeout(300);
await page.getByRole("button", { name: "Settings" }).click();
await page.waitForTimeout(250);
await page.getByText("Themes", { exact: true }).click();
await page.waitForTimeout(600);
await page.screenshot({ path: "/workspace/screenshots/t-themes.png" });
const tiles = await page.locator(".theme-tile").count();
console.log("theme tiles", tiles);
await browser.close();
